# Generated by Django 6.0.4 on 2026-05-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('parking', '0002_alter_parkingrecord_parking_spot'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
